In [3]:
!pip install gensim

   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   - -------------------------------------- 0.8/24.4 MB 8.3 MB/s eta 0:00:03
   --- ------------------------------------ 1.8/24.4 MB 4.8 MB/s eta 0:00:05
   --- ------------------------------------ 2.4/24.4 MB 3.7 MB/s eta 0:00:06
   ------ --------------------------------- 3.7/24.4 MB 4.3 MB/s eta 0:00:05
   ------- -------------------------------- 4.5/24.4 MB 4.3 MB/s eta 0:00:05
   -------- ------------------------------- 5.2/24.4 MB 4.2 MB/s eta 0:00:05
   --------- ------------------------------ 6.0/24.4 MB 4.1 MB/s eta 0:00:05
   ----------- ---------------------------- 6.8/24.4 MB 4.1 MB/s eta 0:00:05
   ------------ --------------------------- 7.9/24.4 MB 4.1 MB/s eta 0:00:05
   -------------- ------------------------- 8.7/24.4 MB 4.1 MB/s eta 0:00:04
   --------------- ------------------------ 9.4/24.4 MB 4.0 MB/s eta 0:00:04
   ---------------- ----------------------- 10.2/24.4 MB 4.1 MB/s eta 0:00:04
   --


[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:

import gensim

In [5]:
from gensim.models import Word2Vec, KeyedVectors

In [6]:
## References: https://stackoverflow.com/questions/46433778/import-googlenews-vectors-negative300-bin

In [9]:
import gensim.downloader as api
print(api.info()['models'].keys())

dict_keys(['fasttext-wiki-news-subwords-300', 'conceptnet-numberbatch-17-06-300', 'word2vec-ruscorpora-300', 'word2vec-google-news-300', 'glove-wiki-gigaword-50', 'glove-wiki-gigaword-100', 'glove-wiki-gigaword-200', 'glove-wiki-gigaword-300', 'glove-twitter-25', 'glove-twitter-50', 'glove-twitter-100', 'glove-twitter-200', '__testing_word2vec-matrix-synopsis'])


In [10]:
import gensim.downloader as api

wv = api.load("glove-wiki-gigaword-50")
print(wv["king"])

[==================================================] 100.0% 66.0/66.0MB downloaded
[ 0.50451   0.68607  -0.59517  -0.022801  0.60046  -0.13498  -0.08813
  0.47377  -0.61798  -0.31012  -0.076666  1.493    -0.034189 -0.98173
  0.68229   0.81722  -0.51874  -0.31503  -0.55809   0.66421   0.1961
 -0.13495  -0.11476  -0.30344   0.41177  -2.223    -1.0756   -1.0783
 -0.34354   0.33505   1.9927   -0.04234  -0.64319   0.71125   0.49159
  0.16754   0.34344  -0.25663  -0.8523    0.1661    0.40102   1.1685
 -1.0137   -0.21585  -0.15155   0.78321  -0.91241  -1.6106   -0.64426
 -0.51042 ]


In [15]:
import gensim.downloader as api
wv = api.load("glove-wiki-gigaword-100")

[==================================================] 100.0% 128.1/128.1MB downloaded


In [16]:
vec_king = wv['king']

In [17]:
vec_king

array([-0.32307 , -0.87616 ,  0.21977 ,  0.25268 ,  0.22976 ,  0.7388  ,
       -0.37954 , -0.35307 , -0.84369 , -1.1113  , -0.30266 ,  0.33178 ,
       -0.25113 ,  0.30448 , -0.077491, -0.89815 ,  0.092496, -1.1407  ,
       -0.58324 ,  0.66869 , -0.23122 , -0.95855 ,  0.28262 , -0.078848,
        0.75315 ,  0.26584 ,  0.3422  , -0.33949 ,  0.95608 ,  0.065641,
        0.45747 ,  0.39835 ,  0.57965 ,  0.39267 , -0.21851 ,  0.58795 ,
       -0.55999 ,  0.63368 , -0.043983, -0.68731 , -0.37841 ,  0.38026 ,
        0.61641 , -0.88269 , -0.12346 , -0.37928 , -0.38318 ,  0.23868 ,
        0.6685  , -0.43321 , -0.11065 ,  0.081723,  1.1569  ,  0.78958 ,
       -0.21223 , -2.3211  , -0.67806 ,  0.44561 ,  0.65707 ,  0.1045  ,
        0.46217 ,  0.19912 ,  0.25802 ,  0.057194,  0.53443 , -0.43133 ,
       -0.34311 ,  0.59789 , -0.58417 ,  0.068995,  0.23944 , -0.85181 ,
        0.30379 , -0.34177 , -0.25746 , -0.031101, -0.16285 ,  0.45169 ,
       -0.91627 ,  0.64521 ,  0.73281 , -0.22752 , 

In [18]:
vec_king.shape

(100,)

In [19]:

wv['cricket']
     

array([-0.55541  ,  0.45894  ,  0.51851  , -0.045938 , -1.4064   ,
        0.49701  , -0.085008 ,  0.63442  , -1.7949   , -0.31881  ,
       -0.13673  , -1.1583   ,  0.45505  ,  0.21464  , -0.21751  ,
       -0.21984  ,  0.60619  ,  0.55812  , -0.01031  ,  0.66228  ,
        0.22206  ,  0.25498  ,  0.8452   , -0.72988  ,  0.26195  ,
        0.26418  ,  0.22577  , -0.051338 ,  0.024459 ,  0.86389  ,
       -0.35585  ,  0.48662  , -0.49752  , -0.44777  , -0.040533 ,
       -0.18376  , -1.32     ,  0.54899  , -1.2289   , -0.22673  ,
       -0.93431  ,  0.78923  ,  0.9565   , -1.3996   ,  1.0314   ,
        0.39573  ,  0.7956   , -0.27184  ,  0.51776  , -1.0387   ,
       -0.38121  ,  0.21772  ,  0.52486  ,  0.63307  , -0.21206  ,
       -1.6741   , -1.3811   ,  0.079469 ,  0.46871  ,  0.29956  ,
       -0.90023  , -0.16781  , -0.30873  ,  0.16586  ,  0.12141  ,
        0.50219  ,  0.049859 ,  0.54896  ,  0.55576  , -0.14683  ,
        0.55657  , -0.0060587,  0.25941  , -0.91918  ,  0.23  

In [20]:
wv.most_similar('cricket')

[('rugby', 0.7827098369598389),
 ('twenty20', 0.7362942099571228),
 ('england', 0.7173773646354675),
 ('indies', 0.715782105922699),
 ('cricketers', 0.7132172584533691),
 ('football', 0.6659637093544006),
 ('zealand', 0.6606222987174988),
 ('matches', 0.6509107351303101),
 ('bowling', 0.6504763960838318),
 ('wc2003-wis', 0.642265260219574)]

In [21]:
wv.most_similar('happy')

[("'m", 0.8413287997245789),
 ('feel', 0.8132575750350952),
 ("'re", 0.8048083186149597),
 ('i', 0.7938276529312134),
 ("'ll", 0.7916273474693298),
 ('really', 0.7903971076011658),
 ('glad', 0.7833361029624939),
 ('good', 0.7821646332740784),
 ('we', 0.7808917164802551),
 ('sure', 0.7788466215133667)]

In [22]:
wv.similarity("hockey","sports")

np.float32(0.6193382)

In [23]:
vec=wv['king']-wv['man']+wv['woman']

In [24]:
vec

array([-0.10231996, -0.81294006,  0.10211003,  0.985924  ,  0.34218282,
        1.09095   , -0.48912996, -0.05616698, -0.21029997, -1.02996   ,
       -0.86851   ,  0.36786997,  0.01960999,  0.59259   , -0.23190099,
       -1.016919  , -0.01218399, -1.17194   , -0.52329   ,  0.60645   ,
       -0.98537004, -1.001028  ,  0.48913902,  0.630072  ,  0.58224   ,
        0.15908998,  0.43685   , -1.25351   ,  0.97054   , -0.065529  ,
        0.733763  ,  0.44219002,  1.2091839 ,  0.19698   , -0.15948   ,
        0.34364003, -0.46222997,  0.33772   ,  0.14792705, -0.24959502,
       -0.77093005,  0.522717  , -0.1283    , -0.91881   , -0.01755001,
       -0.44041002, -0.52656496,  0.33734798,  0.60639   , -0.45067   ,
       -0.04158002,  0.08408299,  1.31456   ,  0.67737997, -0.24316001,
       -2.071     , -0.60648996,  0.19710997,  0.63567   ,  0.07819998,
        0.49161002,  0.08171999,  0.70855707,  0.201938  ,  0.5155501 ,
       -0.23025298, -0.40473002,  0.39212003, -0.5093    , -0.13

In [25]:
wv.most_similar([vec])

[('king', 0.8551837205886841),
 ('queen', 0.783441424369812),
 ('monarch', 0.6933802366256714),
 ('throne', 0.6833109855651855),
 ('daughter', 0.6809081435203552),
 ('prince', 0.6713141798973083),
 ('princess', 0.664408266544342),
 ('mother', 0.6579325795173645),
 ('elizabeth', 0.6563301086425781),
 ('father', 0.6392418742179871)]