In [3]:
import sys
print(sys.version)
print(sys.executable)


3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
c:\Users\Gaurish16\OneDrive\Desktop\Udemy\End-to-end Simple RNN project\venv310\Scripts\python.exe


In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## Define the vocabulary size
voc_size=10000

In [8]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[193, 5363, 6562, 4638],
 [193, 5363, 6562, 9077],
 [193, 354, 6562, 8429],
 [4061, 5240, 313, 6367, 9680],
 [4061, 5240, 313, 6367, 3054],
 [8749, 193, 7455, 6562, 9229],
 [2850, 1366, 9032, 6367]]

In [10]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  193 5363 6562 4638]
 [   0    0    0    0  193 5363 6562 9077]
 [   0    0    0    0  193  354 6562 8429]
 [   0    0    0 4061 5240  313 6367 9680]
 [   0    0    0 4061 5240  313 6367 3054]
 [   0    0    0 8749  193 7455 6562 9229]
 [   0    0    0    0 2850 1366 9032 6367]]


In [13]:
## feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 61ms/step


array([[[ 1.81738250e-02,  4.55151238e-02,  4.75938953e-02,
          9.42205265e-03,  2.31759883e-02,  3.21563743e-02,
         -2.88502704e-02, -5.77354431e-03,  1.18034966e-02,
         -9.42625850e-03],
        [ 1.81738250e-02,  4.55151238e-02,  4.75938953e-02,
          9.42205265e-03,  2.31759883e-02,  3.21563743e-02,
         -2.88502704e-02, -5.77354431e-03,  1.18034966e-02,
         -9.42625850e-03],
        [ 1.81738250e-02,  4.55151238e-02,  4.75938953e-02,
          9.42205265e-03,  2.31759883e-02,  3.21563743e-02,
         -2.88502704e-02, -5.77354431e-03,  1.18034966e-02,
         -9.42625850e-03],
        [ 1.81738250e-02,  4.55151238e-02,  4.75938953e-02,
          9.42205265e-03,  2.31759883e-02,  3.21563743e-02,
         -2.88502704e-02, -5.77354431e-03,  1.18034966e-02,
         -9.42625850e-03],
        [-3.53126302e-02, -1.40279308e-02, -7.96753168e-03,
          2.03002244e-04,  3.12016122e-02,  5.55523485e-03,
          3.15689929e-02,  1.92314126e-02,  2.836084

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0,  193, 5363, 6562, 4638])

In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 27ms/step


array([[ 0.01817382,  0.04551512,  0.0475939 ,  0.00942205,  0.02317599,
         0.03215637, -0.02885027, -0.00577354,  0.0118035 , -0.00942626],
       [ 0.01817382,  0.04551512,  0.0475939 ,  0.00942205,  0.02317599,
         0.03215637, -0.02885027, -0.00577354,  0.0118035 , -0.00942626],
       [ 0.01817382,  0.04551512,  0.0475939 ,  0.00942205,  0.02317599,
         0.03215637, -0.02885027, -0.00577354,  0.0118035 , -0.00942626],
       [ 0.01817382,  0.04551512,  0.0475939 ,  0.00942205,  0.02317599,
         0.03215637, -0.02885027, -0.00577354,  0.0118035 , -0.00942626],
       [-0.03531263, -0.01402793, -0.00796753,  0.000203  ,  0.03120161,
         0.00555523,  0.03156899,  0.01923141,  0.02836085, -0.02454845],
       [-0.01161661, -0.00725074, -0.02432147,  0.0283909 ,  0.0177695 ,
        -0.03088659, -0.03745224, -0.03457345, -0.02212405,  0.01315898],
       [ 0.00367874,  0.02870471, -0.0481333 ,  0.01930059,  0.01505145,
        -0.03714733, -0.00643557,  0.02935053