NumPy (Numerical Python) is a powerful Python library used for numerical and scientific computing. It provides support for large, multi-dimensional arrays and matrices along with a wide collection of mathematical functions to operate on them efficiently. NumPy is much faster and more memory-efficient than regular Python lists because it performs operations in optimized, low-level code. It is widely used in data science, machine learning, artificial intelligence, and scientific research, and it also serves as the foundation for many other Python libraries such as Pandas and SciPy.

In [2]:
!pip install numpy

In [5]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) #1 row and 5 columns (2D)

array([[1, 2, 3, 4, 5]])

In [9]:
arr3=np.array([[1,2,3,4,5]])
arr3.shape

(1, 5)

In [10]:
arr4=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr4)
print(arr4.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# ## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape) # Output: (2, 3)
print("Number of dimensions:", arr.ndim) # Output: 2
print("Size (number of elements):", arr.size) # Output: 6
print("Data type:", arr.dtype) # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize) # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [16]:
# Numpy Vectorized Operation
arr1=np.array((1,2,3,4,5))
arr2=np.array((10,20,30,40,50))

# Element Wise Addition
print("Addition : ", arr1+arr2)

# Element Wise Subraction
print("Subtraction : ", arr2-arr1)

# Element Wise Multiplication
print("Multiplication : ", arr1*arr2)

# Element Wise Division
print("Division : ", arr2/arr1)

Addition :  [11 22 33 44 55]
Subtraction :  [ 9 18 27 36 45]
Multiplication :  [ 10  40  90 160 250]
Division :  [10. 10. 10. 10. 10.]


In [20]:
# Universal Function
arr=np.array((1,2,3,4,5))

# Square Root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [23]:
# Indexing and Slicing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [28]:
# Modify Array Element
arr[0][0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [30]:
arr[1:]=100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [32]:
# Normalization - Statistical Concept
# To have a mean of 0 and standard deviation of 1

data=np.array([1,2,3,4,5])

# Calculate Meand and Standard Deviation
mean=np.mean(data)
sd=np.std(data)

# Normalize the data
normalized_data= (data-mean)/sd
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [33]:
# Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])